marketplace_l6/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


                            //metodo all extendido da classe model dentro da model produto
  //Route::get('/model', function(){

    // $products = \App\Product::all(); //Select * from products (estava assim antes de colocar active record)
      //pela convencao se a classe e product vai procurar products como tabela
      //sempre no plural

      //Active Record = padrao de projeto, cria dados 

      //crio uma instancia de user 
              //passo o caminho todo pois nao importei
      // $user = new \App\User();
      // //o active record permite trabalhar as colunas do banco como se fossem atributos da class

      // $user->name = 'Usuario Teste';
      // $user->email= 'email@teste.com';
      // $user->password = bcrypt('12345678');

    // $user->save();

    //para atualizar
      //  $user = \App\User::find(1); //find busca pelo ID , find = metodo de busca do elouquent

      //  $user->name = 'Usuario Teste Atualizado ....';

      //  $user->save();

      //return \App\User::all(); retorna todos os usuarios
      //serializa = ele converte para json 
      //retorna uma colection que permite fazer diversas operacoes em uma colecao de dados

      //return \App\User::find(3); //retorna um unico usuario com base no id

      //return \App\User::where('name', 'Dr. Alfred Crona')->get(); //select * from users where name = nome
      //nesse caso mesmo oque retorne somente 1 ele retorna em colection
      //porque no caso de nome posso ter repetidos ao contrario de id

      //return \App\User::where('name', 'Dr. Alfred Crona')->first(); // limit 1

      // return \App\User::paginate(10); //traz dez por pagina de all() com link para outras paginas

      //Mass Assigment - Atribuicao em massa (inserirndo usuario)

      //o create espera o nome das colunas e valores como array associativo
      //passo um array que quero inserir na tabela users via model
      // $user = \App\User::create([   //esse create precisa que a model user tenha o atributo filable
      //     'name'  => 'Jean Junior Silva',
      //     'email' => 'jeanjr.silvasousa@gmail.com',
      //     'password' => bcrypt('123456')

      // ]);

      // Mass Update 

      // $user = \App\User::find(42);

      //$user = $user->update([
      //     'name' => 'Atualizando com mass update'
      // ]); //true or false vai retornar se eu atribuir o valor de user para outra variavel user

    // dd($user);

    //COMO EU FARIA PARA PEGAR A LOJA DE UM USUARIO

    // $user = \App\User::find(4);

  //  return $user->store;  //busca o objeto unico store pois a relacao e 1:1
    //se for N:N volta uma colection de dados


    //dd($user->store()->count()); //se fazer como metodo retorna uma instancia de hasone
      //conto quantas lojas o usuario tem


      //PEGAR OS PRODUTOS DE UMA LOJA

      //$loja = \App\Store::find(1);

      //return $loja->products; //retorna uma collection

      // return $loja->products()->count(); //consigo fazer o count a partir do atributo
      //pois o atributo produto ja retorna uma collection


      //PEGAR SOMENTE PRODUTOS DE ID 1 DA LOJA

    //  return $loja->products()->where('id', 1)->get();
      //quando imprime como metodo tem mais possibilidades de dar tratativas na collection

      // dd($loja->products());
    // return \App\User::all(); 

    //PEGAR AS CATEGORIAS DE UMA LOJA

      //$categoria = \App\Category::find(1);

      // return $categoria->products;   // traria todos os produtos da categoria de id 1
      //retorna colecao de dados N:N

  //});

//1 parametro url principal, 2 funcao anonima callback
Route::get('/', 'HomeController@index')->name('home');


Route::get('/product/{slug}', 'HomeController@single')->name('product.single');

Route::get('/category/{slug}', 'CategoryController@index')->name('category.single');

Route::get('/store/{slug}', 'StoreController@index')->name('store.single');

Route::prefix('cart')->name('cart.')->group(function () {

     Route::get('/','CartController@index')->name('index'); 

     Route::post('add', 'CartController@add')->name('add');

     Route::get('remove/{slug}', 'CartController@remove')->name('remove');

     Route::get('cancel', 'CartController@cancel')->name('cancel');

});

Route::prefix('checkout')->name('checkout.')->group(function(){
  
     Route::get('/', 'CheckoutController@index')->name('index');

     Route::post('/process', 'CheckoutController@proccess')->name('proccess');

     Route::get('/thanks', 'CheckoutController@thanks')->name('thanks');

});

Route::get('/model', function(){

      //Criar uma loja para um usuario


  //$user = \App\User::find(10);

                    //vai criar uma loja e receber a referencia do usuario de id 10
                    //cria uma store a partir do relacionamento
  //    $store = $user->store()->create([    //create retorna o objeto com id que recebeu do banco de dados
  //         'name' => 'Loja Teste',
  //         'description' => 'Loja teste de produtos de informatica',
  //         'mobile_phone' => 'XX-XXXX-XXXX',
  //         'phone' => 'XX-XXXX-XXXX',
  //         'slug' => 'loja-teste'
  //     ]);

    //  dd($store);

      

      //Criar um produto para uma loja

  //     $store = \App\Store::find(41);

  //   $product =  $store->products()->create([
  //         'name' => 'Notebook Dell' ,
  //         'description' => 'Core i5 10GB',
  //         'body' => 'Quaquer Coisa',
  //         'price' => 2999.90,
  //         'slug' => 'notebook-dell'
  //     ]);


  //     dd($product);



    //Criar uma categoria

    // \App\Category::create([
    //     'name' => 'Games',
    //     'description' => null,
    //     'slug' => 'games'
    // ]);


    // \App\Category::create([
    //     'name' => 'Notebooks',
    //     'description' => null,
    //     'slug' => 'notebooks'
    // ]);



    //  return \App\Category::all();


    //Adicionar um produto para uma categoria

    $product = \App\Product::find(45);
                //attach adiciona ao produto a categoria de id 1
                //adicionou na tabela category_product
                //para remover use o dettach
  //  dd($product->categories()->attach([1]));

  //  dd($product->categories()->detach([1]));

  //para adicionar mais de uma categoria ao produto use o sync

  //  dd($product->categories()->sync([1,2]));

  // para remover basta tirar o id da categoria  do array
 // dd($product->categories()->sync([2]));

     return $product->categories;   
});

//no laravel responde para as rotas get(recupera), post(cria), put(atualiza) 
//, patch(atualiza), delete, options(dentro do http retorna quais cabecalho a rota especifica responde)


                            //chamando o metodo de um controller no segundo parametro
                            //no exemplo chamo o store controller, coloco duas barras para escapar uma
                            //o metodo chamo com @nomemetodo
                            //para chegar na pasta controller o laravel faz automatico
// Route::get('/admin/stores', 'Admin\\StoreController@index');

//criacao de uma loja
// Route::get('/admin/stores/create', 'Admin\\StoreController@create');

//recebendo dados do formulario
// Route::post('/admin/stores/store', 'Admin\\StoreController@store');


//O admin do inicio da rota ja que esta repetido pode ser substituido pelo prefix
//posso substituir o segundo admin pelo namespace

// Route::prefix('admin')->namespace('Admin')->group(function(){

//   Route::prefix('stores')->group(function(){
//                                          //name = definir um alias para a rota 
//     Route::get('/', 'StoreController@index')->name('admin.stores.index');
  
//     Route::get('/create', 'StoreController@create')->name('admin.stores.create');
  
//     Route::post('/store', 'StoreController@store')->name('admin.stores.store');
//            //parametro dinamico store          //aponta para o metodo edit
//     Route::get('/{store}/edit', 'StoreController@edit')->name('admin.stores.edit');
//                           //store chega no controller como $store
//     Route::post('/update/{store}', 'StoreController@update')->name('admin.stores.update');
//           //get pois vai via url
//     Route::get('/destroy/{store}/', 'StoreController@destroy')->name('admin.stores.destroy');

//   });


// });






//abaixo estou definindo middlewares para um grupo de rotas
//o primeiro parametro sao as middlewares e o segundo a function anonima callback

Route::group(['middleware' => ['auth']], function(){

        //posso colocar mais um name e simplificar

    Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function(){

      // Route::prefix('stores')->name('stores.')->group(function(){
        //                                        //name = definir um alias para a rota 
        //   Route::get('/', 'StoreController@index')->name('index');
        
        //   Route::get('/create', 'StoreController@create')->name('create');
        
        //   Route::post('/store', 'StoreController@store')->name('store');
        //          //parametro dinamico store          //aponta para o metodo edit
        //   Route::get('/{store}/edit', 'StoreController@edit')->name('edit');
        //                         //store chega no controller como $store
        //   Route::post('/update/{store}', 'StoreController@update')->name('update');
        //         //get pois vai via url
        //   Route::get('/destroy/{store}/', 'StoreController@destroy')->name('destroy');

marketplace_l6/resources/views/cart.blade.php
@extends('layouts.front')

@section('content')
   <div class="row">
       <div class="col-12">
           <h2>Carrinho de compras</h2>
           <hr>
       </div>
       <div class="col-12">
           @if ($cart)
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Produto</th>
                        <th>Preço</th>
                        <th>Quantidade</th>
                        <th>Subtotal</th>
                        <th>Ação</th>
                    </tr>
                </thead>
                <tbody>
                    @php $total = 0; @endphp
                    @foreach($cart as $c)
                    <tr>
                        <td>{{$c['name']}}</td>
                        <td>R$ {{number_format($c['price'],2,",","." )}}</td>
                        <td>{{$c['amount']}}</td>
                        @php
                            $subtotal = $c['price'] * $c['amount'];
                            $total+= $subtotal;
                        @endphp
                        <td>R$ {{number_format(($subtotal),2,",","." )}}</td>
                        <td>
                        <a href="{{route('cart.remove', ['slug' => $c['slug']])}}" class="btn btn-sm btn-danger">
                                Remover
                            </a>
                        </td>
                    </tr>
                    @endforeach
                    <tr>
                        <td colspan="3">Total:</td>
                        <td colspan="2">R$ {{number_format(($total),2,",","." )}}</td>
                    </tr>
                </tbody>
            </table>
            <hr>
            <div class="col-md-12">
            <a href="{{route('checkout.index')}}" class="btn btn-lg btn-success pull-right">Concluir Compra</a>
               <a href="{{route('cart.cancel')}}" class="btn btn-lg btn-danger pull-left">Cancelar Compra</a>
            </div>
           @else 
             <div class="alert alert-warning">
                 Carrinho Vazio
             </div>
           @endif
       </div>
   </div>
  


@endsection

marketplace_l6/resources/views/category.blade.php
@extends('layouts.front')

@section('content')
  <div class="row front">
      <div class="col-12">
          <h2>{{$category->name}}</h2>
          <hr>
      </div>
        @forelse($category->products as $key => $product)
        <div class="col-md-4">
            <div class="card" style="width: 100%">
                @if($product->photos->count())
                <img src="{{asset('storage/' . $product->photos->first()->image)}}" alt="" class="card-img-top">
                @else 
                <img src="{{asset('assets/img/no-photo.jpg')}}" alt="" class="card-img-top">
                @endif
                <div class="card-body">
                    <h2 class="card-title">{{$product->name}}</h2>
                    <p class="card-text">{{$product->description}}</p>
                    <h3>
                        R$ {{number_format($product->price,2, ",", ".")}}
                    </h3>
                    <a href="{{route('product.single',['slug' => $product->slug] )}}" class="btn btn-success">
                    Ver Produto
                    </a>
                </div>
            </div>
        </div>
        @if(($key + 1) % 3 == 0) </div><div class="row front"> @endif
        @empty   
        <div class="col-12">
            <h3 class="alert alert-warning">Nenhum produto encontrado para essa categoria</h3>
        </div>
      @endforelse
  </div>

 

@endsection

marketplace_l6/resources/views/checkout.blade.php
@extends('layouts.front')

@section('stylesheets')
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
@endsection

@section('content')

  <div class="container">
      <div class="col-md-6">
          <div class="row">
              <div class="col-md-12">
                  <h2>Dados para pagamento</h2>
                  <hr>
              </div>
          </div>
          <form action="" method="post">
            <div class="row">
                  <div class="col-md-12 form-group">
                      <label>Nome no cartão</label>
                      <input type="text" class="form-control" name="card_name">
                  </div>
              </div>

              <div class="row">
                  <div class="col-md-12 form-group">
                      <label>Número do Cartão <span class="brand"></span></label>
                      <input type="text" class="form-control" name="card_number">
                      <input type="hidden" name="card_brand">
                  </div>
              </div>
    
              <div class="row">
                <div class="col-md-4 form-group">
                    <label>Mês de Expiração</label>
                    <input type="text" class="form-control" name="card_month">
                </div>

                <div class="col-md-4 form-group">
                    <label>Ano de Expiração</label>
                    <input type="text" class="form-control" name="card_year">
                </div>
            </div>

            <div class="row">
                <div class="col-md-5 form-group">
                    <label>Código de Segurança</label>
                    <input type="text" class="form-control" name="card_cvv">
                </div>

                <div class="col-md-12 installments form-group">
                </div>

            </div>

            <button class="btn btn-success btn-lg processCheckout">Efetuar Pagamento</button>
    
          </form>
      </div>
  </div>

@endsection


@section('scripts')
   <script src="https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js"></script>
   <script src="http://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
              crossorigin="anonymous">
    </script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
  
  <script>
//    pegando da nossa sessão o identificador do pag seguro
       const sessionId = '{{session()->get("pagseguro_session_code")}}';
// passando para o pacote de js do proprio pag seguro esse identificador
// passando para lib js
       PagSeguroDirectPayment.setSessionId(sessionId);
   </script>

   <script>
       let amountTransaction = '{{$cartItems}}';
       let cardNumber = document.querySelector('input[name=card_number]');
       let spanBrand = document.querySelector('span.brand');

          //evento keyup é quando o usuario digita e tira dedo da tecla
       cardNumber.addEventListener('keyup', function(){
           if(cardNumber.value.length >= 6){
            PagSeguroDirectPayment.getBrand({
                //informo digitos do cartao para o metodo
                cardBin: cardNumber.value.substr(0,6),
                        //function callback com result
                success: function(res){
                    let imgFlag = `<img src="https://stc.pagseguro.uol.com.br/public/img/payment-methods-flags/68x30/${res.brand.name}.png" />`;
                    spanBrand.innerHTML = imgFlag;
                    document.querySelector('input[name=card_brand]').value = res.brand.name;

                    getInstallments(amountTransaction, res.brand.name);
                },

                error: function(err) {
                    console.log(err);
                },

                complete: function(res){
                   // console.log('Complete: ', res);
                }

            });
           };
       });


       let submitButton = document.querySelector('button.processCheckout');


       submitButton.addEventListener('click', function(event){
          
           //não executa o evento padrao de submit do botão
           event.preventDefault();
           //pagseguroDirectPayment = classe do sdk pag seguro
           // o metodo create card token vai buscar o token para esse cartão
           PagSeguroDirectPayment.createCardToken({
               cardNumber:      document.querySelector('input[name=card_number]').value ,
               brand:           document.querySelector('input[name=card_brand]').value  ,
               cvv:             document.querySelector('input[name=card_cvv]').value ,
               expirationMonth: document.querySelector('input[name=card_month]').value ,
               expirationYear:  document.querySelector('input[name=card_year]').value ,

               success: function(res){
                   proccessPayment(res.card.token);
               }

           });
       })

       function proccessPayment(token)
       {
             //get sender hash vai retornar um hash que identifica o usuario para requisicao
             //de pagemento
             let data = {
                 card_token: token,
                 hash: PagSeguroDirectPayment.getSenderHash(),
                 installment: document.querySelector('select.select_installments').value,
                 card_name: document.querySelector( 'input[name=card_name]').value,
                 _token: '{{csrf_token()}}'
             }

             $.ajax({
                url: '{{route("checkout.proccess")}}',
                type: 'post',
                data: data,
                datatype: 'json',

                success: function(res){
                    toastr.success(res.data.message, 'Sucesso');
                    window.location.href = '{{route("checkout.thanks")}}?order='+res.data.order;
                }

             });
       }

       //função de opções de parcelamento vai pegar total da venda e 
       //bandeira
       function getInstallments(amount, brand)
       {
           //  PagSeguroDirectPayment = classe java script do pagseguro
           //maxInstallmentNoInterest: quantidade de parcelas que assumimos o jutos
           PagSeguroDirectPayment.getInstallments({
               amount: amount,
               brand: brand,
               //essa chave max = o maximo de parcelas sem juros 
               //ou seja assumo o juros p/ cliente
               maxInstallmentNoInterest: 0,

               success: function(res){
                   let selectInstallments = drawSelectInstallments(res.installments[brand]);

                   document.querySelector('div.installments').innerHTML = selectInstallments;
               },

               error: function(err){
                    console.log(err);
               },

                complete: function(res){

                },

           })
         

       }


       function drawSelectInstallments(installments) {
		let select = '<label>Opções de Parcelamento:</label>';

		select += '<select class="form-control select_installments">';

        //igual foreach do php
		for(let l of installments) {
		    select += `<option value="${l.quantity}|${l.installmentAmount}">${l.quantity}x de ${l.installmentAmount} - Total fica ${l.totalAmount}</option>`;
		}


		select += '</select>';

		return select;
	   }
   </script>


@endsection

marketplace_l6/resources/views/single.blade.php
@extends('layouts.front')

@section('content')
   <div class="row">
       <div class="col-6">
           @if($product->photos->count())
            <img src="{{asset('storage/' . $product->photos->first()->image)}}" alt="" class="card-img-top">
            <div class="row" style="margin-top: 20px">
                @foreach($product->photos as $photo)
                    <div class="col-4">
                        <img src="{{asset('storage/' . $photo->image)}}" alt="" class="img-fluid">
                    </div>
                @endforeach
            </div>
           @else   
             <img src="{{asset('assets/img/no-photo.jpg')}}" alt="" class="card-img-top">
           @endif
        </div>
       <div class="col-6">
         <div class="col-md-12">
            <h2>{{$product->name}}</h2>
            <p>
              {{$product->description}}
            </p>
  
            <h3>
                R$ {{number_format($product->price,2, ",", ".")}}
            </h3>
            <span>
                Loja: {{$product->store->name}}
            </span>
         </div>   

         <div class="product-add col-md-12">
             <hr>
             <!-- A rota cart add vai armazenar o produto em sessão -->
         <form action="{{route('cart.add')}}" method="post">
             @csrf
             <input type="hidden" name="product[name]" value="{{$product->name}}">
             <input type="hidden" name="product[price]" value="{{$product->price}}">
             <input type="hidden" name="product[slug]" value="{{$product->slug}}">
                 <div class="form-group">
                    <label>Quantidade</label>
                    <input type="number" value="1" name="product[amount]" class="form-control col-md-2">
                 </div>
                 <button  class="btn btn-lg btn-danger">Comprar</button>
             </form>
         </div>
       </div>
   </div>
   <div class="row">
       <div class="col-12">
           <hr>
           {{$product->body}}
       </div>
   </div>
@endsection

marketplace_l6/resources/views/store.blade.php
@extends('layouts.front')

@section('content')
  <div class="row front">
         <div class="col-4">
            @if($store->logo)
            <img src="{{asset('storage/' . $store->logo)}}" alt="Logo da loja {{$store->name}}" class="img-fluid">
           @else
           <img src="https://via.placeholder.com/600X300.png?text=logo" alt="Loja sem logo..." class="img-fluid">
           @endif
         </div>
          <div class="col-8">
            <h2>{{$store->name}}</h2>
            <p>{{$store->description}}</p>
            <p>
                 <strong>Contatos:</strong>
                <span>{{$store->phone}}</span> | <span>{{$store->mobile_phone}}</span>
            </p>
          </div>
          <div class="col-12">
              <hr>
              <h3 style="margin-bottom: 30px">Produtos desta loja</h3>
      </div>
      
        @forelse($store->products as $key => $product)
        <div class="col-md-4">
            <div class="card" style="width: 100%">
                @if($product->photos->count())
                <img src="{{asset('storage/' . $product->photos->first()->image)}}" alt="" class="card-img-top">
                @else 
                <img src="{{asset('assets/img/no-photo.jpg')}}" alt="" class="card-img-top">
                @endif
                <div class="card-body">
                    <h2 class="card-title">{{$product->name}}</h2>
                    <p class="card-text">{{$product->description}}</p>
                    <h3>
                        R$ {{number_format($product->price,2, ",", ".")}}
                    </h3>
                    <a href="{{route('product.single',['slug' => $product->slug] )}}" class="btn btn-success">
                    Ver Produto
                    </a>
                </div>
            </div>
        </div>
        @if(($key + 1) % 3 == 0) </div><div class="row front"> @endif
        @empty   
        <div class="col-12">
            <h3 class="alert alert-warning">Nenhum produto encontrado para essa loja</h3>
        </div>
      @endforelse
  </div>

 

@endsection

marketplace_l6/resources/views/thanks.blade.php
@extends('layouts.front')

@section('content')
   <h2 class="alert alert-success">
      Muito obrigado por sua compra!
   </h2>
   <h3>
    Seu pedido foi processado, código do pedido: {{request()->get('order')}}.
   </h3>
@endsection